name: .NET Core CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: github4women

      - name: Build the project
        run: dotnet build --no-restore --configuration Release
        working-directory: github4women

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        working-directory: github4women

      - name: Run custom script
        run: |
          echo "Running custom script..."
          dotnet --version
          echo "Custom script completed."
        working-directory: github4women